version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: pact-postgres
    environment:
      POSTGRES_USER: pactbroker
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: pactbroker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pact-broker:
    image: pactfoundation/pact-broker
    container_name: pact-broker
    depends_on:
      - postgres
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh
    command: ["/bin/sh", "-c", "/wait-for-it.sh postgres:5432 -- bundle exec puma -C config/puma.rb"]
    environment:
      PACT_BROKER_DATABASE_ADAPTER: postgres
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: pactbroker
      PACT_BROKER_DATABASE_USERNAME: pactbroker
      PACT_BROKER_DATABASE_PASSWORD: yourpassword
    ports:
      - "9292:9292"

volumes:
  postgres_data: